#!/usr/bin/python

import roslib
roslib.load_manifest('sparton_ahrs8')
import rospy
from std_msgs.msg import Header, String
from geometry_msgs.msg import Quaternion, Vector3
from sensor_msgs.msg import Imu, MagneticField

import traceback
import math

import numpy
import serial

g0 = 9.80665

rospy.init_node('sparton_ahrs8')

frame_id = rospy.get_param('~frame_id', '/imu')
port = rospy.get_param('~port', '/dev/imu')

s = serial.Serial(port, 115200)
s.write('printmask magp_trigger accelp_trigger or gyrop_trigger or set drop\r\n')
s.write('printmodulus 1 set drop\r\n')
s.write('gyroSigma f0.0 set drop\r\n')
s.write('printtrigger gyrop_trigger set drop\r\n')


pub = rospy.Publisher('/imu/data_raw', Imu)
mag_pub = rospy.Publisher('/imu/mag_raw', MagneticField)
raw_pub = rospy.Publisher('/imu/raw', String)


def handle_line(data, now):
    try:
        # P:,257925,mp,168.249969,23.194071,479.150848,ap,40.882568,-248.846878,970.272583,gp,0.000050,0.000001,0.000019,T,27.56
        raw_pub.publish(data)
        const_P_colon, timestamp, const_mp, mag_x, mag_y, mag_z, const_ap, acc_x, acc_y, acc_z, const_gp, gyro_x, gyro_y, gyro_z = data.split(',')
        assert const_P_colon == 'P:'
        assert const_mp == 'mp'
        assert const_ap == 'ap'
        assert const_gp == 'gp'
        timestamp, mag_x, mag_y, mag_z, acc_x, acc_y, acc_z, gyro_x, gyro_y, gyro_z = map(float, [timestamp, mag_x, mag_y, mag_z, acc_x, acc_y, acc_z, gyro_x, gyro_y, gyro_z])
    except Exception:
        print repr(data)
        traceback.print_exc()
        return
    mag_x, mag_y, mag_z = [1e-7 * x for x in [mag_x, mag_y, mag_z]]
    acc_x, acc_y, acc_z = [-1e-3 * g0 * x for x in [acc_x, acc_y, acc_z]]
    gyro_x, gyro_y, gyro_z = [110.447762 * x for x in [gyro_x, gyro_y, gyro_z]]
    pub.publish(Imu(
        header=Header(
            stamp=now,
            frame_id=frame_id,
        ),
        orientation=Quaternion(0, 0, 0, 0),
        orientation_covariance=[-1] + [0]*8,
        angular_velocity=Vector3(gyro_x, gyro_y, gyro_z),
        angular_velocity_covariance=[.03**2,0,0, 0,.03**2,0, 0,0,.03**2], # XXX
        linear_acceleration=Vector3(acc_x, acc_y, acc_z),
        linear_acceleration_covariance=[.02**2,0,0, 0,.02**2,0, 0,0,.02**2], # XXX
    ))

    mag_pub.publish(MagneticField(
        header=Header(
            stamp=now,
            frame_id=frame_id,
        ),
        magnetic_field=Vector3(mag_x, mag_y, mag_z),
    ))



tmpdata = ''
while not rospy.is_shutdown():
    waiting = s.inWaiting()
    now = rospy.Time.now()
    tmpdata += s.read(waiting) # blocking seems to break things, strangely
    x = tmpdata.split('\n')
    tmpdata = x[-1]
    for data in x[:-1]:
        handle_line(data, now)
