function data = importfile(workbookFile, sheetName, range)
%IMPORTFILE Import numeric data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.
%
%	Non-numeric cells are replaced with: 0.0
%
% Example:
%   data =
%   importfile('_slash_z_drive_dbg_msg.csv','_slash_z_drive_dbg_msg','A2:AG1183');
%	rosbagTimestamp = data(:,1);
%   controlmethod = data(:,2);
%	xcurrent = data(:,3);
%   xdesired = data(:,4);
%	ycurrent = data(:,5);
%   ydesired = data(:,6);
%	xvelocitycurrent = data(:,7);
%    ...
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/06/13 22:14:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, range);

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) ~isnumeric(x) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
data = cell2mat(raw);

