function output = SteepestDescent(input, preinput, Fxref, Fyref, Mref, rx1, rx2, ry1, ry2, C)

% global rx1 rx2 ry1 ry2 C;
% global Fxref Fyref Mref;

theta1  = input(1);
f1      = input(2);
theta2  = input(3);
f2      = input(4);

pretheta1   = preinput(1);
pretheta2   = preinput(3);

dVdtheta1 = C(3)*(f1*ry1*cosd(theta1)...
    - f1*rx1*sind(theta1))*(f1*rx1*cosd(theta1)...
    - Mref + f2*rx2*cosd(theta2) + f1*ry1*sind(theta1)...
    + f2*ry2*sind(theta2)) - C(6)*(pretheta1 - theta1)...
    - C(2)*f1*sind(theta1)*(f1*cosd(theta1) - Fyref + f2*cosd(theta2))...
    + C(1)*f1*cosd(theta1)*(Fxref + f1*sind(theta1) + f2*sind(theta2));

dVdf1 = C(4)*f1 + C(1)*sind(theta1)*(Fxref + f1*sind(theta1)...
    + f2*sind(theta2)) + C(2)*cosd(theta1)*(f1*cosd(theta1) - Fyref...
    + f2*cosd(theta2)) + C(3)*(rx1*cosd(theta1)...
    + ry1*sind(theta1))*(f1*rx1*cosd(theta1) - Mref + f2*rx2*cosd(theta2)...
    + f1*ry1*sind(theta1) + f2*ry2*sind(theta2));

dVdtheta2 = C(3)*(f2*ry2*cosd(theta2)...
    - f2*rx2*sind(theta2))*(f1*rx1*cosd(theta1)...
    - Mref + f2*rx2*cosd(theta2) + f1*ry1*sind(theta1)...
    + f2*ry2*sind(theta2)) - C(7)*(pretheta2 - theta2)...
    - C(2)*f2*sind(theta2)*(f1*cosd(theta1) - Fyref + f2*cosd(theta2))...
    + C(1)*f2*cosd(theta2)*(Fxref + f1*sind(theta1) + f2*sind(theta2));

dVdf2 = C(5)*f2 + C(1)*sind(theta2)*(Fxref + f1*sind(theta1)...
    + f2*sind(theta2)) + C(2)*cosd(theta2)*(f1*cosd(theta1) - Fyref...
    + f2*cosd(theta2)) + C(3)*(rx2*cosd(theta2)...
    + ry2*sind(theta2))*(f1*rx1*cosd(theta1) - Mref + f2*rx2*cosd(theta2)...
    + f1*ry1*sind(theta1) + f2*ry2*sind(theta2));
 
output = -[dVdtheta1; dVdf1; dVdtheta2; dVdf2];

end