# The forces and torques defined in this message are RELATIVE to the BOAT's coordinate frame
float64 outside_force_x
float64 outside_force_y
float64 outside_force_z
# outside roll torque to place on the simulator's boat
float64 outside_torque_r
# outside pitch torque to place on the simulator's boat
float64 outside_torque_p
# outside yaw torque to place on the simulator's boat
float64 outside_torque_y
