#!/usr/bin/env python

from __future__ import division

import math
import numpy
import random
import traceback
import rospy

import ode
import pygame
from OpenGL.GL import *
from OpenGL.GLU import *
from twisted.internet import protocol, reactor, task

import roslib
roslib.load_manifest('boatsim')
import rospy
import tf
from nav_msgs.msg import Odometry
from geometry_msgs.msg import Point, Vector3, Quaternion, WrenchStamped
from sensor_msgs.msg import LaserScan
from std_msgs.msg import Float64
from std_msgs.msg import Header
from uf_common import interpolate
from sim import threed, vector, util
from sim.vector import v, V

from boatsim import devices

rospy.init_node('boatsim')

'''
from visualization_msgs.msg import MarkerArray,Marker
global buoy_array
buoy_publisher=rospy.Publisher('buoys',MarkerArray)
buoy_array=MarkerArray()
'''

thruster_param_names = ['motor_driver_FR', 'motor_driver_FL', 'motor_driver_BR', 'motor_driver_BL']
thruster_infos = None
thrusters = [0]*len(thruster_param_names)
for i in xrange(len(thruster_param_names)):
    reactor.listenTCP(10030 + i, util.AutoServerFactory(devices.ThrusterProtocol, i, thrusters))


clip = lambda x, (low, high): min(max(x, low), high)

def buoyancy_force(depth, r):    
    inf = 1e1000
    assert math.isinf(inf)
    sphere_antiderivative = lambda h: -h**3*math.pi/3 + h*math.pi*r**2
    sphere_true_antiderivative = lambda h: sphere_antiderivative(clip(h, (-r, r)))
    vol_submerged = sphere_true_antiderivative(depth) - sphere_true_antiderivative(-inf)
    return 1000 * 9.81 * vol_submerged

world, world_time = ode.World(), reactor.seconds()
world.setGravity((0, 0, -9.81))

body = ode.Body(world)
M = ode.Mass()
M.setBoxTotal(47, 1.27, .46, .46)
body.setMass(M)
body.setPosition((0, 0, 0))
body.setQuaternion(vector.axisangle_to_quat(v(0, 0, 1), math.pi/2))

space = ode.HashSpace()

body_geom = ode.GeomBox(space, (1.27, .46, .46))
body_geom.setBody(body)

lake_mesh = threed.mesh_from_obj(roslib.packages.resource_file('boatsim', 'models', 'lake.obj'))
lake_geom = ode.GeomTriMesh(lake_mesh.ode_trimeshdata, space)

def get_water_vel(pos):
    return v(0, 0, 0)
    return (pos % v(0, 0, 1))*math.e**(-pos.mag()/3)

killed = False
locked = False

odom_pub = rospy.Publisher('/sim_odom', Odometry)
base_tf_br = tf.TransformBroadcaster()

class lidar:
    def __init__(self):
        '''
        This class constitutes a lidar object. It is packaged with:
            - Ranging "ray-tracer"
            - Laserscan publisher
            - TF publisher
        
        Future:
            To make it a more generic, useful object
                - Rotation and relative position must be settable
                - Inspiration: 'Threed' camera view
        '''

        ##TODO: This neesd to be made more generic for use with sub imaging sonar
        
        self.lidar_pub = rospy.Publisher('/lidar_range', LaserScan)
        self.lidar_tf_br = tf.TransformBroadcaster()
        #rospy.Publisher('scan_complete',Bool)
        #The above is used in another laserscan, not sure how necessary it is
    
        self.pitch = 0

    def pitch_lidar(self):
        max_pitch = math.radians(10)
        min_pitch = math.radians(-10)
        
        pitch_inc = math.radians(2)

        if self.pitch > min_pitch:
            self.pitch -= pitch_inc
        else:
            self.pitch = max_pitch
    
    def send_lidar_transform(self):
        '''
        Publishes a transformation on /base_link/laser
            -> Allows LIDAR data taken at an arbitrary angle (or position) to be viewed from the
            base_link (The boat body) reference frame.

        Reference code at laser_tf_broadcaster.py in sensors package
            (If you are looking for tf reference code, try grep -r "TransformBroadcaster" in the root uf-mil directory)
        '''
        ##TODO: 
        # Clean this up, share tf xyz/pitch with publish/scanner
        # OOP this up!
        bl_lu_x       = 0.8001        # Distance forward, BaseLink to Lidar Unit
        bl_lu_y       = 0     # Distance left, BaseLink to Lidar Unit
        bl_lu_z       = 0.254         # Distance up, BaseLink to Lidar Unit
        lu_r          = 0             # Roll of Lidar Unit
        lu_p          = 0             # Pitch of Lidar Unit
        lu_y          = 0             # Yaw of Lidar Unit
        lu_lp_x       = 0             # Distance forward, Lidar Unit to Lidar Pivot
        lu_lp_y       = 0             # Distance left, Lidar Unit to Lidar Pivot
        lu_lp_z       = 0             # Distance up, Lidar Unit to Lidar Pivot
        lp_r          = 0             # Roll of Lidar Pivot
        lp_y          = 0             # Yaw of Lidar Pivot
        lp_lm_x       = 0.0127        # Distance forward, Lidar Pivot to Lidar Mirror
        lp_lm_y       = 0             # Distance left, Lidar Pivot to Lidar Mirror
        lp_lm_z       = 0.0317        # Distance up, Lidar Pivot to Lidar Mirror

        lp_p = self.pitch

        T = tf.transformations.translation_matrix((lp_lm_x, lp_lm_y, lp_lm_z))
        T = tf.transformations.rotation_matrix((lp_y), (0, 0, 1)).dot(T)
        T = tf.transformations.rotation_matrix((lp_p), (0, 1, 0)).dot(T)
        T = tf.transformations.rotation_matrix((lp_r), (1, 0, 0)).dot(T)
        T = tf.transformations.translation_matrix((lu_lp_x, lu_lp_y, lu_lp_z)).dot(T)
        T = tf.transformations.rotation_matrix((lu_y), (0, 0, 1)).dot(T)
        T = tf.transformations.rotation_matrix((lu_p), (0, 1, 0)).dot(T)
        T = tf.transformations.rotation_matrix((lu_r), (1, 0, 0)).dot(T)
        T = tf.transformations.translation_matrix((bl_lu_x, bl_lu_y, bl_lu_z)).dot(T)
        T = tf.transformations.translation_from_matrix(T)
        #-> There's got to be a less ugly way to do this


        total_roll = lu_r + lp_r
        total_pitch = lu_p + lp_p
        total_yaw = lu_y + lp_y
        
        self.lidar_tf_br.sendTransform(
                T,
                tf.transformations.quaternion_from_euler(total_roll, total_pitch, total_yaw),
                rospy.Time.now(),
                "/base_link/laser",
                "/base_link"
                )

    def get_lidar_range(self):
        '''
        get_lidar_range(nothing) -> distances
        
        Behavior:
        
            This function will publish distance to the nearest object,
            in accordance with the current orientation of the dynamixel servos
            It will automatically cull the boat geom from the list of distances
        
        Functionality:
            
            Distances are computed using ode collision space, where the distance is
            the point to point distance between the origin of the ray and the point on the geom
            that the ray intersects with
        
        Future:
            
            - Variable pitch (Sub on /lidar_angle topic)
            - Fake intensities (Based on distance, no need to go crazy)

        Lidar Simulated Features:
             
            Field of view:                        270 deg
            Scanning frequency:                   25 Hz / 50 Hz    
            Angular resolution:                   0.25 deg 0.5 deg
            Operating range:                      0.5 m to 20 m    
            Max. range with 10 % reflectivity:    18 m    
            Amount of evaluated echoes:           2
        '''
         
        lidar_FOV = 270 #deg
        lidar_scanrate = 25.0 #hz
        lidar_ang_res = 0.25 #deg
        lidar_range = 20.0
        #lidar_range = 100
        lidar_end_angle = math.radians((lidar_FOV/2.0))
        lidar_start_angle = math.radians(-(lidar_FOV/2.0))

        def publish_lidar(scan_ranges_in, intensity_list_in = []):
            self.lidar_pub.publish(
                LaserScan(
                    header = Header(
                        stamp=rospy.Time.now(), 
                        frame_id="/base_link/laser" 
                    ),
                    angle_min = lidar_start_angle,
                    angle_max = lidar_end_angle,
                    angle_increment = math.radians(lidar_ang_res),
                    scan_time = 1.0/lidar_scanrate,
                    range_min = 0.5,
                    range_max = lidar_range,
                    ranges = scan_ranges_in,
                    intensities = intensity_list_in,
                )
            )

        #raylength = 1e3
        raylength = lidar_range + 0.2*lidar_range
        lidar_scanrate = 100
        #Space - ?
        ray = ode.GeomRay(None, raylength)
        # Had to do conversions, couldn't find a metric ruler
        # This vector is the physical offset of the LIDAR module from the center of the boat
        lidar_pos = v(0.8001,0.0,0.254) 

        # Pre-initialize the array
        scan_ranges = [None]*int(lidar_FOV/lidar_ang_res)
        intensity_list = [None]*len(scan_ranges)

        for i in range(len(scan_ranges)):
            
            closest_distance = 1000
            projection_angle = math.radians(i*lidar_ang_res) - math.radians(lidar_FOV/2.0)
            
            x_hat = math.cos(projection_angle)
            y_hat = math.sin(projection_angle)
            z_hat = math.sin(self.pitch)
            
            lidar_ray_dir = body.vectorToWorld(v(x_hat, y_hat ,-z_hat))

            ray.set( body.getRelPointPos(lidar_pos), lidar_ray_dir )
            list_dist = []
            for contact in ode.collide(ray,space):
                # Position = XYZ
                # Normal = normal vector to detected surface
                # Dist = distance to object
                # Geom1 = the ray
                # Geom2 = the detected object geometry
                stamp = rospy.Time.now()
                pos,normal,dist,geom1,geom2 = contact.getContactGeomParams()
                assert geom1 is ray, geom1
                if geom2 is lake_mesh:
                    continue
                valid_distance =  (V(pos) - V(body.getRelPointPos(lidar_pos))).mag()
                #Can't get away without append (maybe preallocate large list)
                #Taking repeated minimum isn't going to cut it either
                #There's no guarantee that they'll come in order, apparently.
                list_dist.append(valid_distance)

            if len(list_dist) > 0:
                closest_distance = min(list_dist)

            scan_ranges[i] = closest_distance
            intensity_list[i] = 20

        self.send_lidar_transform()
        publish_lidar(scan_ranges)
        self.pitch_lidar()

#Instantiate a "Lidar" instance.
boat_lidar = lidar()

def world_tick():
    global world_time, thruster_infos
    
    boat_lidar.get_lidar_range() # Use and publish whoa!

    water_vel = get_water_vel(V(body.getPosition()))
    
    body.addForceAtRelPos((0, 0, buoyancy_force(-body.getPosition()[2], 0.22728849402137372)), (0, 0, .1))
    body.addForce(-(40 if body.getPosition()[2] >= 0 else 10) * (V(body.getLinearVel())-water_vel))
    #body.addForce([random.gauss(0, 1) for i in xrange(3)])
    #body.addTorque([random.gauss(0, 10) for i in xrange(3)])
    body.addTorque(-(20 if body.getPosition()[2] >= 0 else 5) * V(body.getAngularVel()))
    
    #print thrusters
    
    sub_model.vectors = []
    if thruster_infos is None:
        try:
            thruster_infos = [rospy.get_param(param) for param in thruster_param_names]
        except:
            pass
    else:
        for info, value in zip(thruster_infos, thrusters):
            relpos = V(info['position'])
            reldir = V(info['direction'])
            force = interpolate.sample_curve((info['output_list'], info['force_list']), value)
            #print info['id'], force
            body.addRelForceAtRelPos(reldir*force, relpos)
            sub_model.vectors.append((relpos, relpos - .02*reldir*force))
    
    keys = pygame.key.get_pressed()
    for keycode, force in [
        (pygame.K_k, v(-50, 0, 0)),
        (pygame.K_i, v(+50, 0, 0)),
        (pygame.K_j, v(0, +50, 0)),
        (pygame.K_l, v(0, -50, 0)),
        (pygame.K_o, v(0, 0, +50)),
        (pygame.K_m, v(0, 0, -50)),
    ]:
        if keys[keycode]:
            body.addRelForce(force*(10 if keys[pygame.K_RSHIFT] else 1)*(.1 if keys[pygame.K_RCTRL] else 1))
    for keycode, torque in [
        (pygame.K_COMMA, v(-20, 0, 0)),
        (pygame.K_u, v(+20, 0, 0)),
        (pygame.K_h, v(0, +20, 0)),
        (pygame.K_SEMICOLON, v(0, -20, 0)),
        (pygame.K_0, v(0, 0, +20)),
        (pygame.K_n, v(0, 0, -20)),
    ]:
        if keys[keycode]:
            body.addRelTorque(torque*(10 if keys[pygame.K_RSHIFT] else 1)*(.1 if keys[pygame.K_RCTRL] else 1))
    
    global killed
    if keys[pygame.K_1]:
        killed = True
    if keys[pygame.K_2]:
        killed = False
    global locked
    if keys[pygame.K_3]:
        locked = True
    if keys[pygame.K_4]:
        locked = False
    
    contactgroup = ode.JointGroup()
    
    if locked:
        j = ode.FixedJoint(world, contactgroup)
        j.attach(body, None)
        j.setFixed()
    
    near_pairs = []
    space.collide(None, lambda _, geom1, geom2: near_pairs.append((geom1, geom2)))
    for geom1, geom2 in near_pairs:
        for contact in ode.collide(geom1, geom2):
            contact.setBounce(0.2)
            contact.setMu(5000)
            j = ode.ContactJoint(world, contactgroup, contact)
            j.attach(geom1.getBody(), geom2.getBody())
    
    dt = 1/30
    world.step(dt)
    world_time += dt
    
    contactgroup.empty()
    
    msg = Odometry()
    msg.header.stamp = rospy.Time(world_time)
    msg.header.frame_id = '/map'
    msg.child_frame_id = '/base_link'
    msg.pose.pose.position = Point(*body.getPosition())
    q = V(body.getQuaternion())
    msg.pose.pose.orientation = Quaternion(q[1], q[2], q[3], q[0])
    msg.twist.twist.linear = Vector3(*q.conj().quat_rot(body.getLinearVel()))
    msg.twist.twist.angular = Vector3(*q.conj().quat_rot(body.getAngularVel()))
    odom_pub.publish(msg)
    

    rpy_u = tf.transformations.euler_from_quaternion(q)
    rpy = (0, 0, rpy_u[2])

    #print body.getPosition()
    T = tf.transformations.translation_matrix(body.getPosition())
    T = tf.transformations.rotation_matrix((rpy[2]), (0, 0, 1)).dot(T)
    T = tf.transformations.rotation_matrix((rpy[1]), (0, 1, 0)).dot(T)
    T = tf.transformations.rotation_matrix((rpy[0]), (1, 0, 0)).dot(T)
    #T = tf.transformations.translation_matrix((bl_lu_x, bl_lu_y, bl_lu_z)).dot(T)
    T = tf.transformations.translation_from_matrix(T)
    #->


    #T = tf.transformations.translation_matrix((lp_lm_x, lp_lm_y, lp_lm_z))
    #T = tf.transformations.rotation_matrix((lp_y), (0, 0, 1)).dot(T)
    #T = tf.transformations.rotation_matrix((lp_p), (0, 1, 0)).dot(T)
    #T = tf.transformations.rotation_matrix((lp_r), (1, 0, 0)).dot(T)
    #T = tf.transformations.translation_matrix((lu_lp_x, lu_lp_y, lu_lp_z)).dot(T)
    #T = tf.transformations.rotation_matrix((lu_y), (0, 0, 1)).dot(T)
    #T = tf.transformations.rotation_matrix((lu_p), (0, 1, 0)).dot(T)
    #T = tf.transformations.rotation_matrix((lu_r), (1, 0, 0)).dot(T)
    #T = tf.transformations.translation_matrix((bl_lu_x, bl_lu_y, bl_lu_z)).dot(T)
    #T = tf.transformations.translation_from_matrix(T)

    #bl_lu_x       = 0.8001        # Distance forward, BaseLink to Lidar Unit
    #bl_lu_y       = 0     # Distance left, BaseLink to Lidar Unit
    #bl_lu_z       = 0.254         # Distance up, BaseLink to Lidar Unit
    #lu_r          = 0             # Roll of Lidar Unit
    #lu_p          = 0             # Pitch of Lidar Unit
    #lu_y          = 0             # Yaw of Lidar Unit
    #lu_lp_x       = 0             # Distance forward, Lidar Unit to Lidar Pivot
    #lu_lp_y       = 0             # Distance left, Lidar Unit to Lidar Pivot
    #lu_lp_z       = 0             # Distance up, Lidar Unit to Lidar Pivot
    #lp_r          = 0             # Roll of Lidar Pivot
    #lp_y          = 0             # Yaw of Lidar Pivot
    #lp_lm_x       = 0.0127        # Distance forward, Lidar Pivot to Lidar Mirror
    #lp_lm_y       = 0             # Distance left, Lidar Pivot to Lidar Mirror
    #lp_lm_z       = 0.0317        # Distance up, Lidar Pivot to Lidar Mirror
    base_tf_br.sendTransform(
            T,
            #tf.transformations.quaternion_from_euler(total_roll, total_pitch, total_yaw),
            #q,
            tf.transformations.quaternion_from_euler(rpy[0],rpy[1],rpy[2]),
            rospy.Time.now(),
            "/base_link", 
            "/map",
            )
    
    reactor.callLater(max(0, world_time + dt - reactor.seconds()), world_tick)



class Boat(object):
    is_base_link = True
    
    def __init__(self, body, is_killed_func):
        self.body = body
        self.is_killed_func = is_killed_func
        self.vectors = []
    
    def draw(self):
        with threed.GLMatrix:
            threed.rotate_to_body(self.body)
            
            q = gluNewQuadric()
            with threed.GLMatrix:
                glTranslate(+.2, 0, 0)
                glColor3f(0, 1, 0)
                gluSphere(q, 0.5, 40, 20)
            with threed.GLMatrix:
                glTranslate(-.2, 0, 0)
                glColor3f(1, 0, 0)
                gluSphere(q, 0.5, 40, 20)
            with threed.GLMatrix:
                glTranslate(+.4, -.2, +.3)
                glColor3f(0, 0, 0)
                gluSphere(q, 0.1, 40, 20)
            with threed.GLMatrix:
                glTranslate(+.4, +.2, +.3)
                glColor3f(0, 0, 0)
                gluSphere(q, 0.1, 40, 20)
            with threed.GLMatrix:
                glTranslate(0, 0, +.5)
                if self.is_killed_func():
                    glColor3f(1, 0, 0)
                else:
                    glColor3f(0, 1, 0)
                gluSphere(q, 0.1, 20, 10)
            
            glDisable(GL_DEPTH_TEST)
            glBegin(GL_LINES)
            for start, end in self.vectors:
                glColor3f(0, 0, 0)
                glVertex3f(*start)
                glColor3f(1, 1, 1)
                glVertex3f(*end)
            glEnd()
            glEnable(GL_DEPTH_TEST)
            

def generate_buoy_pair(world, pos,angle):
    
    channel_gap = 2
    green_pos = (pos[0] + math.cos(math.radians(angle))*(channel_gap/2.),pos[1] + math.sin(math.radians(angle))*(channel_gap/2.))
    red_pos = (pos[0] - math.cos(math.radians(angle))*(channel_gap/2.),pos[1] - math.sin(math.radians(angle))*(channel_gap/2.))
    
    world.objs.append(Buoys(v(green_pos[0], green_pos[1], 0),(0,1,0)))
    world.objs.append(Buoys(v(red_pos[0], red_pos[1], 0),(1,0,0)))
   
class Buoys(object):
    def __init__(self, pos,color):
       global buoy_array
       #self.buoys = [(pos + [random.gauss(0, 5), random.gauss(0, 5), 0], color) for i in xrange(10) for color in [(1, 0, 0), (0, 1, 0),(0,0,1)]]
       #self.buoys = [(pos + [i*3,0,0],(i,1-i,0)) for i in xrange(2)]
       self.buoys = [pos,color] 
    def draw(self):
        q = gluNewQuadric()
        #for pos, color in self.buoys:
        with threed.GLMatrix:
            glTranslate(*self.buoys[0])
            glColor3f(*self.buoys[1])
            gluSphere(q, .2, 30, 15)

w = threed.World()

w.objs.append(lake_mesh)
sub_model = Boat(body, lambda: killed)
w.objs.append(sub_model)
w.objs.append(threed.VectorField(get_water_vel))
generate_buoy_pair(w, (2,1),0)
generate_buoy_pair(w, (10,5),15)
generate_buoy_pair(w, (15,10),60)

'''
i.objs.append(Buoys(v(-1, 5, 0)))
i.objs.append(Buoys(v(-5, 10, 0)))
i.objs.append(Buoys(v(-2, 15, 0)))
'''
def set_forward_view():
    glTranslate(-2.8, 0, 0)
    threed.rotate_to_body(body, inv=True)
c1 = threed.Camera(w, "mv_bluefox_camera_node", set_forward_view, body, fovy=90)
#Guessed topic name based on vision src contents(Jake)

def set_forward_view2():
    glTranslate(-2.4, 0.1, 0.1)
    threed.rotate_to_body(body, inv=True)
c2 = threed.Camera(w, 'fwd_camera_2', set_forward_view2, body, fovy=50)
#Guessed topic name based on dice roll(Jake)
#-> Add correct offsets

newbuoy_mesh = threed.mesh_from_obj(roslib.packages.resource_file('boatsim', 'models', 'green_buoy.obj'))
newbuoy_mesh = newbuoy_mesh.translate((5, 5, 0))
w.objs.append(newbuoy_mesh)
newbuoy_geom = ode.GeomTriMesh(newbuoy_mesh.ode_trimeshdata, space)

cruciform_mesh = threed.mesh_from_obj(roslib.packages.resource_file('boatsim', 'models', 'cruciform.obj'))
cruciform_mesh = cruciform_mesh.translate((10, 5, 0))
w.objs.append(cruciform_mesh)
cruciform_geom = ode.GeomTriMesh(cruciform_mesh.ode_trimeshdata, space)

circle_mesh = threed.mesh_from_obj(roslib.packages.resource_file('boatsim', 'models', 'circle.obj'))
circle_mesh = circle_mesh.translate((10, 5, .66))
w.objs.append(circle_mesh)
circle_geom = ode.GeomTriMesh(circle_mesh.ode_trimeshdata, space)

triangle_mesh = threed.mesh_from_obj(roslib.packages.resource_file('boatsim', 'models', 'triangle.obj'))
triangle_mesh = triangle_mesh.translate((10, 5, 1.33))
w.objs.append(triangle_mesh)
triangle_geom = ode.GeomTriMesh(triangle_mesh.ode_trimeshdata, space)

i = threed.Interface()
i.init(w)
def _():
    try:
        i.step()
        c1.step()
        c2.step()
    except:
        traceback.print_exc()
        reactor.stop()
reactor.callWhenRunning(task.LoopingCall(_).start, 1/24)

reactor.callWhenRunning(world_tick)

reactor.callWhenRunning(lambda: rospy.core.add_client_shutdown_hook(lambda reason=None: reactor.callFromThread(reactor.stop)))
reactor.run()
